[package]
name = "indexer"
version = "0.1.0"
authors = ["dusk <y.bera003.06@pm.me>"]
license = "MIT"
edition = "2021"
resolver = "2"

[dependencies]
cargo = "0.61"
curl = { version = "0.4", features = ["http2"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"