name: "Nix"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
jobs:
  regenerate-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: dream2nix-crates-io
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Index 5k most downloaded packages
      run: nix run .#index-top-5k-downloads
    - name: Translate locks
      run: |
        rm -rf ./gen/locks
        JOBS=20 nix run .#translate
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore: regenerate index & lock files"
        branch: main
